apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: backend
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword123
  MYSQL_DATABASE: university_db
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword123
