name: Build and Deploy Apps

on:
  pull_request:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: hasanAbdirahman
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------- FRONTEND ----------
      - name: Build frontend image
        run: |
          docker build --build-arg REACT_APP_API_URL=http://backend-service:5000 \
          -t $DOCKERHUB_USERNAME/frontend-student:$IMAGE_TAG ./frontend
          docker push $DOCKERHUB_USERNAME/frontend-student:$IMAGE_TAG

      # ---------- BACKEND ----------
      - name: Build backend image
        run: |
          docker build -t $DOCKERHUB_USERNAME/backend-student:$IMAGE_TAG ./backend
          docker push $DOCKERHUB_USERNAME/backend-student:$IMAGE_TAG

      # ---------- UPDATE K8S MANIFESTS ----------
      - name: Update Kubernetes manifests
        run: |
          sed -i "s|REPLACE_ME|$IMAGE_TAG|g" k8s/frontend/deployment.yaml
          sed -i "s|REPLACE_ME|$IMAGE_TAG|g" k8s/backend/deployment.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s
          git commit -m "Deploy images $IMAGE_TAG"
          git push
